<?php
session_start();
include 'config.php';

// Security Check
if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'Admin') {
    header("Location: login.php");
    exit;
}

// --- LOGIC 3: REPORT GENERATION ---
$start_date = isset($_GET['start']) ? $_GET['start'] : date('Y-m-01');
$end_date = isset($_GET['end']) ? $_GET['end'] : date('Y-m-t');
$report_type = isset($_GET['type']) ? $_GET['type'] : 'Appointments';

// Get Current User for "Generated By"
$generated_by = $_SESSION['name'];
$date_printed = date('F d, Y h:i A');

// --- DATA FETCHING & SUMMARY ---
$data = [];
$summary = [];

if ($report_type == 'Appointments') {
    $sql = "SELECT a.*, p.name FROM appointment a JOIN patient p ON a.patient_id = p.patient_id WHERE a.appointment_date BETWEEN '$start_date' AND '$end_date' ORDER BY a.appointment_date DESC";
    $res = $conn->query($sql);
    if($res) while($r = $res->fetch_assoc()) $data[] = $r;

    $summary['total'] = count($data);
    $summary['completed'] = count(array_filter($data, fn($r) => $r['status'] == 'Completed'));
    $summary['cancelled'] = count(array_filter($data, fn($r) => $r['status'] == 'Cancelled'));
    $summary['pending'] = count(array_filter($data, fn($r) => $r['status'] == 'Pending'));

} elseif ($report_type == 'Sales') {
    $sql = "(SELECT DATE(bill_date) as pay_date, bill_id as ref_id, p.name, paid_amount as amount, payment_method as method, 'Service Balance' as type, NULL as appointment_status
             FROM billing b 
             JOIN patient p ON b.patient_id = p.patient_id 
             WHERE DATE(b.bill_date) BETWEEN '$start_date' AND '$end_date' AND b.status='Paid')
            UNION ALL
            (SELECT a.appointment_date as pay_date, a.appointment_id as ref_id, p.name, 
                    CASE 
                        WHEN a.payment_mode = 'Full' THEN sp.price
                        ELSE sp.price * 0.5
                    END as amount, 
                    'Deposit' as method, 
                    CASE 
                        WHEN a.status = 'Cancelled' THEN 'Cancelled Booking Downpayment'
                        ELSE 'Booking Downpayment'
                    END as type,
                    a.status as appointment_status
             FROM appointment a 
             JOIN patient p ON a.patient_id = p.patient_id 
             LEFT JOIN service_pricing sp ON a.service = sp.service_name
             WHERE a.appointment_date BETWEEN '$start_date' AND '$end_date' 
             AND a.down_payment_status='Paid'
             AND sp.price IS NOT NULL)
            ORDER BY pay_date DESC";
    
    $res = $conn->query($sql);
    if($res) while($r = $res->fetch_assoc()) $data[] = $r;

    $summary['total_revenue'] = array_sum(array_column($data, 'amount'));
    $summary['transactions'] = count($data);
    $summary['avg_transaction'] = $summary['transactions'] > 0 ? $summary['total_revenue'] / $summary['transactions'] : 0;
    
} elseif ($report_type == 'Patients') {
    $sql = "SELECT * FROM patient ORDER BY patient_id DESC";
    $res = $conn->query($sql);
    if($res) while($r = $res->fetch_assoc()) $data[] = $r;
    
    $summary['total_patients'] = count($data);
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Report - MCMIS</title>
    
    <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <script src="https://cdn.tailwindcss.com?plugins=forms"></script>
    <!-- PDF Generation Library -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>

    <script>
        tailwind.config = {
            darkMode: "class",
            theme: {
                extend: {
                    colors: { "primary": "#3b82f6", "surface": "#ffffff", "background": "#f3f4f6", "text-main": "#1e293b", "text-sub": "#64748b", "border": "#e2e8f0" },
                    fontFamily: { "display": ["Manrope", "sans-serif"], "body": ["Roboto", "sans-serif"] }
                }
            }
        }
    </script>

    <style>
        /* --- PRINT STYLING --- */
        @media print {
            #sidebar, #overlay, .no-print { display: none !important; }
            body, .flex-1 { background: white !important; margin: 0 !important; padding: 0 !important; overflow: visible !important; height: auto !important; }
            main { padding: 0 !important; margin: 0 !important; width: 100% !important; max-width: 100% !important; }
            #print-header { display: block !important; margin-bottom: 20px; border-bottom: 2px solid #333; padding-bottom: 10px; }
            #print-summary { display: flex !important; margin-bottom: 20px; gap: 20px; }
            .summary-card { border: 1px solid #ccc !important; padding: 10px !important; flex: 1; }
            table { width: 100% !important; border-collapse: collapse !important; font-size: 11px; }
            th, td { border: 1px solid #ddd !important; padding: 6px !important; color: black !important; }
            th { background-color: #f0f0f0 !important; font-weight: bold !important; }
            #print-footer { display: block !important; margin-top: 50px; }
        }
        #print-header, #print-footer, #print-summary { display: none; }
    </style>
</head>
<body class="bg-background text-text-main font-body h-screen overflow-hidden flex flex-col md:flex-row">

    <aside id="sidebar" class="w-64 bg-surface border-r border-border flex-col h-screen fixed md:static z-50 hidden md:flex">
        <div class="p-6 flex items-center gap-3 border-b border-border/50 h-16">
            <div class="size-8 bg-primary/10 rounded-lg flex items-center justify-center text-primary"><i class="fas fa-heartbeat text-lg"></i></div>
            <span class="font-display font-bold text-lg text-text-main">MCMIS Clinic</span>
        </div>
        <nav class="flex-1 p-3 space-y-1">
            <a href="admin_dashboard.php?tab=users" class="flex items-center gap-3 px-3 py-2.5 rounded-lg text-text-sub hover:bg-primary/5 hover:text-primary transition-colors">
                <i class="fas fa-users-cog w-5 text-center"></i><span class="text-sm font-medium">User Management</span>
            </a>
            <a href="admin_dashboard.php?tab=reports" class="flex items-center gap-3 px-3 py-2.5 rounded-lg bg-primary/10 text-primary border-l-4 border-primary transition-colors">
                <i class="fas fa-chart-bar w-5 text-center"></i><span class="text-sm font-medium">Generate Reports</span>
            </a>
            <a href="logout.php" class="flex items-center gap-3 px-3 py-2.5 rounded-lg text-red-500 hover:bg-red-50 transition-colors mt-auto">
                <i class="fas fa-sign-out-alt w-5 text-center"></i><span class="text-sm font-medium">Logout</span>
            </a>
        </nav>
    </aside>

    <div class="flex-1 flex flex-col h-full overflow-hidden">
        
        <header class="h-16 bg-surface border-b border-border flex items-center justify-between px-6 shrink-0 z-10 no-print">
            <h1 class="font-display font-bold text-xl text-text-main">System Reports</h1>
            <div class="text-sm text-text-sub bg-primary/10 px-3 py-1 rounded-full border border-primary/20">
                <i class="fas fa-user-shield mr-2 text-primary"></i> Admin Panel
            </div>
        </header>

        <main class="flex-1 overflow-y-auto bg-background p-4 md:p-6 lg:p-8">
            <div class="max-w-6xl mx-auto space-y-6">

                <section class="bg-surface rounded-xl shadow-sm border border-border p-5 no-print">
                    <form method="GET" class="flex flex-wrap items-end gap-4">
                        <div class="flex-1 min-w-[200px]">
                            <label class="block text-xs font-bold text-text-sub uppercase mb-1">Report Type</label>
                            <select name="type" class="w-full text-sm border-border rounded-lg focus:ring-primary focus:border-primary">
                                <option value="Appointments" <?php if($report_type=='Appointments') echo 'selected'; ?>>Appointment History</option>
                                <option value="Sales" <?php if($report_type=='Sales') echo 'selected'; ?>>Sales / Income Report</option>
                                <option value="Patients" <?php if($report_type=='Patients') echo 'selected'; ?>>Registered Patients</option>
                            </select>
                        </div>
                        <div class="flex-1 min-w-[150px]">
                            <label class="block text-xs font-bold text-text-sub uppercase mb-1">Start Date</label>
                            <input type="date" name="start" value="<?php echo $start_date; ?>" class="w-full text-sm border-border rounded-lg focus:ring-primary focus:border-primary">
                        </div>
                        <div class="flex-1 min-w-[150px]">
                            <label class="block text-xs font-bold text-text-sub uppercase mb-1">End Date</label>
                            <input type="date" name="end" value="<?php echo $end_date; ?>" class="w-full text-sm border-border rounded-lg focus:ring-primary focus:border-primary">
                        </div>
                        <button type="submit" class="px-6 py-2.5 bg-primary text-white text-sm font-semibold rounded-lg hover:bg-blue-600 transition-shadow shadow-sm">
                            <i class="fas fa-filter mr-2"></i> Filter Data
                        </button>
                    </form>
                </section>

                <section class="bg-surface rounded-xl shadow-md border border-border overflow-hidden p-8" id="report-area">
                    
                    <!-- PRINT HEADER -->
                    <div id="print-header" class="text-center">
                        <div class="flex items-center justify-center gap-3 mb-2">
                             <div style="font-size:24px;">🏥</div>
                            <h1 class="text-2xl font-bold text-black uppercase">MCMIS Maternity Clinic</h1>
                        </div>
                        <p class="text-sm text-gray-600">123 Health Avenue, San Jose del Monte, Bulacan</p>
                        <p class="text-sm text-gray-600">Contact: (044) 123-4567 | Email: info@mcmis.com</p>
                        <br>
                        <h2 class="text-xl font-bold text-black uppercase border-t border-black pt-4 mb-4"><?php echo strtoupper($report_type); ?> SUMMARY REPORT</h2>
                        <div class="flex justify-between text-xs font-mono mb-4">
                            <span><strong>Period:</strong> <?php echo date('M d, Y', strtotime($start_date)) . " - " . date('M d, Y', strtotime($end_date)); ?></span>
                            <span><strong>Generated:</strong> <?php echo $date_printed; ?></span>
                        </div>
                    </div>

                    <!-- SCREEN HEADER -->
                    <div class="flex justify-between items-center mb-6 no-print">
                        <div>
                            <h2 class="font-display font-bold text-lg text-text-main"><?php echo $report_type; ?> Report Overview</h2>
                            <p class="text-sm text-text-sub">Period: <?php echo date('M d, Y', strtotime($start_date)); ?> — <?php echo date('M d, Y', strtotime($end_date)); ?></p>
                        </div>
                        <div class="flex gap-2">
                            <button onclick="downloadPDF()" class="px-4 py-2 bg-red-50 text-red-600 border border-red-100 text-sm font-bold rounded-lg hover:bg-red-100 transition-colors flex items-center gap-2">
                                <i class="fas fa-file-pdf"></i> Download PDF
                            </button>
                            <button onclick="window.print()" class="px-4 py-2 bg-white border border-border text-text-main text-sm font-medium rounded-lg hover:bg-gray-50 transition-colors flex items-center gap-2 shadow-sm">
                                <i class="fas fa-print"></i> Print
                            </button>
                        </div>
                    </div>

                    <!-- SUMMARY CARDS (Both Screen & Print) -->
                    <?php if($report_type == 'Sales'): ?>
                        <div class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6" id="summary-cards">
                            <div class="p-5 bg-green-50 rounded-xl border border-green-100 summary-card">
                                <p class="text-xs font-bold text-green-600 uppercase">Total Revenue</p>
                                <p class="text-2xl font-extrabold text-green-700 mt-1">₱<?php echo number_format($summary['total_revenue'], 2); ?></p>
                            </div>
                            <div class="p-5 bg-blue-50 rounded-xl border border-blue-100 summary-card">
                                <p class="text-xs font-bold text-blue-600 uppercase">Transactions</p>
                                <p class="text-2xl font-extrabold text-blue-700 mt-1"><?php echo $summary['transactions']; ?></p>
                            </div>
                            <div class="p-5 bg-indigo-50 rounded-xl border border-indigo-100 summary-card">
                                <p class="text-xs font-bold text-indigo-600 uppercase">Avg. Transaction</p>
                                <p class="text-2xl font-extrabold text-indigo-700 mt-1">₱<?php echo number_format($summary['avg_transaction'], 2); ?></p>
                            </div>
                        </div>
                    <?php elseif($report_type == 'Appointments'): ?>
                         <div class="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6" id="summary-cards">
                            <div class="p-4 bg-gray-50 rounded-xl border border-gray-200 summary-card">
                                <p class="text-xs font-bold text-gray-500 uppercase">Total</p>
                                <p class="text-xl font-extrabold text-gray-700 mt-1"><?php echo $summary['total']; ?></p>
                            </div>
                            <div class="p-4 bg-green-50 rounded-xl border border-green-200 summary-card">
                                <p class="text-xs font-bold text-green-600 uppercase">Completed</p>
                                <p class="text-xl font-extrabold text-green-700 mt-1"><?php echo $summary['completed']; ?></p>
                            </div>
                            <div class="p-4 bg-yellow-50 rounded-xl border border-yellow-200 summary-card">
                                <p class="text-xs font-bold text-yellow-600 uppercase">Pending</p>
                                <p class="text-xl font-extrabold text-yellow-700 mt-1"><?php echo $summary['pending']; ?></p>
                            </div>
                            <div class="p-4 bg-red-50 rounded-xl border border-red-200 summary-card">
                                <p class="text-xs font-bold text-red-600 uppercase">Cancelled</p>
                                <p class="text-xl font-extrabold text-red-700 mt-1"><?php echo $summary['cancelled']; ?></p>
                            </div>
                        </div>
                    <?php endif; ?>

                    <!-- DATA TABLE -->
                    <div class="overflow-x-auto">
                        <table class="w-full text-left border-collapse">
                            <thead>
                                <tr class="bg-gray-50 border-b border-gray-200 text-xs font-bold uppercase tracking-wider text-gray-600">
                                    <?php if($report_type == 'Appointments'): ?>
                                        <th class="px-4 py-3">Date</th><th class="px-4 py-3">Time</th><th class="px-4 py-3">Patient Name</th><th class="px-4 py-3">Status</th>
                                    <?php elseif($report_type == 'Sales'): ?>
                                        <th class="px-4 py-3">Date</th><th class="px-4 py-3">Ref ID</th><th class="px-4 py-3">Patient Name</th><th class="px-4 py-3">Amount</th><th class="px-4 py-3">Method</th>
                                    <?php else: ?>
                                        <th class="px-4 py-3">ID</th><th class="px-4 py-3">Full Name</th><th class="px-4 py-3">Contact Number</th><th class="px-4 py-3">Account Type</th>
                                    <?php endif; ?>
                                </tr>
                            </thead>
                            <tbody class="divide-y divide-gray-100 text-sm">
                                <?php
                                if(empty($data)) {
                                    echo "<tr><td colspan='5' class='text-center py-8 text-gray-400 italic'>No records found.</td></tr>";
                                } else {
                                    foreach($data as $row) {
                                        if ($report_type == 'Appointments') {
                                            $st_class = 'bg-gray-100 text-gray-600';
                                            if($row['status'] == 'Completed') $st_class = 'bg-green-100 text-green-800';
                                            if($row['status'] == 'Cancelled') $st_class = 'bg-red-100 text-red-800';
                                            if($row['status'] == 'Pending') $st_class = 'bg-yellow-100 text-yellow-800';
                                            
                                            echo "<tr>
                                                <td class='px-4 py-3'>{$row['appointment_date']}</td>
                                                <td class='px-4 py-3'>".date('h:i A', strtotime($row['appointment_time']))."</td>
                                                <td class='px-4 py-3 font-bold'>{$row['name']}</td>
                                                <td class='px-4 py-3'><span class='px-2 py-1 rounded text-xs font-bold $st_class'>{$row['status']}</span></td>
                                            </tr>";
                                        } 
                                        elseif ($report_type == 'Sales') {
                                            $badge_class = 'bg-green-50 text-green-700 border-green-100';
                                            if (strpos($row['type'], 'Downpayment') !== false) $badge_class = 'bg-indigo-50 text-indigo-700 border-indigo-100';
                                            if ($row['type'] == 'Cancelled Booking Downpayment') $badge_class = 'bg-orange-50 text-orange-700 border-orange-100';
                                            
                                            echo "<tr class='hover:bg-gray-50/50'>
                                                <td class='px-4 py-3 font-medium'>".date('M d, Y', strtotime($row['pay_date']))."</td>
                                                <td class='px-4 py-3 font-mono text-xs'>
                                                    <span class='block text-gray-400'>#{$row['ref_id']}</span>
                                                    <span class='px-2 py-0.5 rounded-full border text-[9px] font-bold uppercase $badge_class'>{$row['type']}</span>
                                                </td>
                                                <td class='px-4 py-3'>{$row['name']}</td>
                                                <td class='px-4 py-3 font-bold text-gray-900'>₱".number_format($row['amount'], 2)."</td>
                                                <td class='px-4 py-3'><span class='text-xs bg-gray-100 px-2 py-1 rounded text-gray-600'>{$row['method']}</span></td>
                                            </tr>";
                                        }
                                        else {
                                             echo "<tr>
                                                <td class='px-4 py-3 font-mono text-xs'>{$row['patient_id']}</td>
                                                <td class='px-4 py-3 font-semibold'>{$row['name']}</td>
                                                <td class='px-4 py-3'>{$row['contact_no']}</td>
                                                <td class='px-4 py-3 text-gray-500'>Client</td>
                                            </tr>";
                                        }
                                    }
                                    
                                    // Total Footer for Sales
                                    if ($report_type == 'Sales') {
                                         echo "<tr class='bg-gray-50 font-bold border-t border-gray-200'>
                                                 <td colspan='3' class='px-4 py-3 text-right text-gray-600 uppercase tracking-wider text-xs'>Grand Total:</td>
                                                 <td colspan='2' class='px-4 py-3 text-green-600 text-xl font-extrabold'>₱".number_format($summary['total_revenue'], 2)."</td>
                                               </tr>";
                                    }
                                }
                                ?>
                            </tbody>
                        </table>
                    </div>

                    <!-- PRINT FOOTER -->
                    <div id="print-footer">
                        <div class="flex justify-between items-end">
                            <div class="text-xs text-gray-500">
                                <p>System Generated Report</p>
                                <p>MCMIS Clinic System v2.0</p>
                            </div>
                            <div class="text-center">
                                <div class="border-b border-black w-48 mb-1"></div>
                                <p class="text-sm font-bold uppercase"><?php echo $generated_by; ?></p>
                                <p class="text-xs text-gray-600">Administrator Signature</p>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </main>
    </div>

    <!-- SCRIPT FOR PDF -->
    <script>
    function downloadPDF() {
        // Clone the element to modify slightly for PDF download if needed (e.g., removing shadows)
        // But html2canvas usually handles it fine.
        
        const element = document.getElementById('report-area');
        
        // Configuration for html2pdf
        const opt = {
          margin:       0.3,
          filename:     'MCMIS_<?php echo $report_type; ?>_Report_<?php echo $end_date; ?>.pdf',
          image:        { type: 'jpeg', quality: 0.98 },
          html2canvas:  { scale: 2, useCORS: true },
          jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' }
        };

        // Add a class to force print styles (optional, but CSS @media print is usually better ignored by html2pdf default)
        // html2pdf snapshots the visible DOM mostly.
        
        // We temporarily show the hidden print header for the PDF snapshot
        const printHeader = document.getElementById('print-header');
        const printFooter = document.getElementById('print-footer');
        
        const originalHeaderDisplay = printHeader.style.display;
        const originalFooterDisplay = printFooter.style.display;
        
        printHeader.style.display = 'block';
        printFooter.style.display = 'block';
        
        // Temporarily hide the "Screen Header" with download buttons
        document.querySelector('.no-print').style.display = 'none';

        // Generate
        html2pdf().set(opt).from(element).save().then(() => {
            // Revert changes
            printHeader.style.display = '';
            printFooter.style.display = '';
             document.querySelector('.no-print').style.display = ''; // Revert to flex/block whatever
             location.reload(); // Simplest way to ensure UI is clean
        });
    }
    </script>
</body>
</html>